apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ec-app
  namespace: flask-ec-app
  labels:
    app: flask-ec-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-ec-app
  template:
    metadata:
      labels:
        app: flask-ec-app
    spec:
      containers:
      - name: flask-app
        image: <YOUR_ECR_REPO_URL>/flask-ec-app:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-ec-app-secrets
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: flask-ec-app-secrets
              key: DATABASE_URL
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: flask-ec-app-secrets
              key: NEW_RELIC_LICENSE_KEY
        - name: NEW_RELIC_ENVIRONMENT
          value: "production"
        - name: NEW_RELIC_APP_NAME
          value: "Flask EC App"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ecr-registry-secret
