"""Add bulk user management fields to users table

Revision ID: 1571b224fa7b
Revises: d6930813d341
Create Date: 2025-10-27 13:40:46.357730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1571b224fa7b'
down_revision = 'd6930813d341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add columns with default values first
        batch_op.add_column(sa.Column('is_test_user', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('test_batch_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_by_bulk', sa.Boolean(), nullable=True))
    
    # Update existing users to have default values
    op.execute("UPDATE users SET is_test_user = false WHERE is_test_user IS NULL")
    op.execute("UPDATE users SET created_by_bulk = false WHERE created_by_bulk IS NULL")
    
    # Now make the columns NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_test_user', nullable=False)
        batch_op.alter_column('created_by_bulk', nullable=False)
        
        # Add indexes for better query performance
        batch_op.create_index('idx_users_test_batch', ['test_batch_id'])
        batch_op.create_index('idx_users_is_test', ['is_test_user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Drop indexes first
        batch_op.drop_index('idx_users_is_test')
        batch_op.drop_index('idx_users_test_batch')
        
        # Then drop columns
        batch_op.drop_column('created_by_bulk')
        batch_op.drop_column('test_batch_id')
        batch_op.drop_column('is_test_user')

    # ### end Alembic commands ###
